Default: &defaults
  user: tp4
  password: tp4
  host: localhost
  database: tp4
  connections: 10

Development:
  <<: *defaults

Testing:
  database: tp4_test
  <<: *defaults

Staging:
  database: tp4_staging
  connections: 100
  <<: *defaults

Production:
  database: tp4_production
  connections: 100
  host: localhost
  <<: *defaults
